# fly.toml app configuration file generated for punchcafe-gandalf-billowing-flower-9732 on 2024-02-18T18:44:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'punchcafe-gandalf'
primary_region = 'lhr'

[build]
  image = 'punchcafe/gandalf:0.1.0'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
